### ISSUE TITLE
Layout checklist

### ISSUE THREAD

**Issue by bindebende** [bindebende/TypeCPD_To_UART#6]
TPS55165:
- [ ] Place decoupling capacitors as close as possible to the input
- [ ] Make the power flow in a straight path rather than a zigzag path on the board.
- [ ] Use the PGND pin, GND pin, and the device PowerPAD as the single-point connection between the analog and power grounds
- [ ] Use eight to nine via holes with a 0.3 mm diameter in the device PowerPAD to help dissipate heat through
- [ ] Use at least ten via holes with a 0.3 mm diameter around the input and output capacitors that are connected to ground-plane layers to minimize the PCB impedance for power current flows
